server:
    contextPath: /
    port: 8083
########################################################
###THYMELEAF (ThymeleafAutoConfiguration)
########################################################
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML5
#spring.thymeleaf.encoding=UTF-8
# ;charset=<encoding> is added
#spring.thymeleaf.content-type=text/html
# set to false for hot refresh
spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
    application:
        name: oracleDb
    profiles:
        active: native
    datasource:
        driverClassName: oracle.jdbc.OracleDriver
        #url: jdbc:oracle:thin:@172.20.1.19:1521:XE
        url: jdbc:oracle:thin:@localhost:1521:MYTEST
        username: root
        password: root
    devtools: # DEVTOOLS (DevToolsProperties)
            livereload:
                enabled: true # Enable a livereload.com compatible server.
                port: 35729 # Server port.
            restart:
                additional-exclude: # Additional patterns that should be excluded from triggering a full restart.
                additional-paths: # Additional paths to watch for changes.
                enabled: true # Enable automatic restart.
                exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties # Patterns that should be excluded from triggering a full restart.
                poll-interval: 1000 # Amount of time (in milliseconds) to wait between polling for classpath changes.
                quiet-period: 400 # Amount of quiet time (in milliseconds) required without any classpath changes before a restart is triggered.
                trigger-file:  # Name of a specific file that when changed will trigger the restart check. If not specified any classpath file change will trigger the restart.




data:
    serverType: oracle

